### ISSUE TITLE
Not compatible with lwt/lwt_log >= 4.0.0

### ISSUE THREAD

**Issue by mseri** [xapi-project/nbd#126]
Nbd needs changes to support lwt after the split between Lwt and Lwt_log. The new recommended way is to use log and fmt, lwt_log will be deprecated soon

**Comment by gaborigloi** [comment]
We have https://github.com/xapi-project/nbd/issues/113 for moving to `logs` :)

**Comment by gaborigloi** [comment]
I think we do support the new `lwt_log` because it's been added to the opam and dune files.
