### ISSUE TITLE
Make sure that the magic constants have the exact same form as defined in the NBD protocol

### ISSUE THREAD

**Issue by gaborigloi** [xapi-project/nbd#90]
https://github.com/xapi-project/nbd/blob/27764ae3c36e1139db8cc074fa7ed796bc723ddc/lib/protocol.ml#L243

To make it easier to verify that we obey the NBD protocol. If we just have these random numbers, they can easily be off-by-one for example.

**Comment by thomassa** [comment]
Agreed: the protocol doc describes these as 2^31 - n where n is 1,2,3,4...

**Comment by gaborigloi** [comment]
It turns out that OCaml doesn't have unsigned ints, but we could do
```
Int32.(shift_left (of_int 1) 31) + 5
```
for example, as the protocol says:
> There are a number of error reply types, all of which are denoted by
having bit 31 set.

So this would probably be more readable and easier to verify than the original.
